name: coverity

on:
  push:
    branches: [ coverity ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-22.04
    env:
      WITH_AOM: 1
      WITH_DAV1D: 1
      WITH_GRAPHICS: 1
      WITH_LIBDE265: 1
      WITH_RAV1E: 0
      WITH_X265: 1
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      with:
        persist-credentials: false

    - name: Get checksum of the current Coverity build tool
      id: coverity-md5
      env:
        TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
      run: |
        md5=$(curl -sSf --data "token=$TOKEN&project=strukturag%2Flibheif&md5=1" https://scan.coverity.com/download/linux64)
        echo "md5=$md5" >> "$GITHUB_OUTPUT"

    - name: Cache Coverity build tool
      id: coverity-cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 #v6.1.0
      with:
        path: coverity_tool.tar.gz
        key: coverity-tool-${{ runner.os }}-${{ steps.coverity-md5.outputs.md5 }}

    - name: Download Coverity build tool
      if: steps.coverity-cache.outputs.cache-hit != 'true'
      env:
        TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
      run: |
        curl -sSfL --data "token=$TOKEN&project=strukturag%2Flibheif" -o coverity_tool.tar.gz https://scan.coverity.com/download/linux64

    - name: Unpack Coverity build tool
      run: |
        mkdir coverity_tool
        tar xzf coverity_tool.tar.gz --strip 1 -C coverity_tool

    - name: Install dependencies
      run: |
        ./scripts/install-ci-linux.sh

    - name: Prepare CI
      run: |
        ./scripts/prepare-ci.sh

    - name: Build with Coverity build tool
      run: |
        export PATH=$(pwd)/coverity_tool/bin:$PATH
        export PKG_CONFIG_PATH="$(pwd)/libde265/dist/lib/pkgconfig/:$(pwd)/third-party/rav1e/dist/lib/pkgconfig/:$(pwd)/third-party/dav1d/dist/lib/x86_64-linux-gnu/pkgconfig/"
        cmake --preset=develop .
        cov-build --dir cov-int make -j$(nproc)

    - name: Submit build result to Coverity Scan
      env:
        TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
      run: |
        tar czvf libheif.tar.gz cov-int
        curl --form token=$TOKEN \
          --form email=opensource@struktur.de \
          --form file=@libheif.tar.gz \
          --form version="Commit $GITHUB_SHA" \
          --form description="Build submitted via CI" \
          https://scan.coverity.com/builds?project=strukturag%2Flibheif
