name: mingw

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  mingw:
    strategy:
      matrix:
        env:
          - { MINGW: 32 }
          - { MINGW: 64 }
    env: ${{ matrix.env }}
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        ./scripts/install-ci-linux.sh

    - name: Prepare CI
      run: |
        ./scripts/prepare-ci.sh

    - name: Run tests
      run: |
        ./scripts/run-ci.sh
