/*
 * HEIF codec.
 * Copyright (c) 2024-2025 Dirk Farin <dirk.farin@gmail.com>
 *
 * This file is part of libheif.
 *
 * libheif is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 *
 * libheif is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with libheif.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef LIBHEIF_HEIF_UNCOMPRESSED_H
#define LIBHEIF_HEIF_UNCOMPRESSED_H

#include "libheif/heif_uncompressed_types.h"
#include "libheif/heif.h"

#ifdef __cplusplus
extern "C" {
#endif

/* @file heif_uncompressed.h
 * @brief Functions for adding ISO 23001-17 (uncompressed) images to a HEIF file.
 *        Despite its name, this is not limited to uncompressed images.
 *        It is also possible to add images with lossless compression methods.
 *        See heif_metadata_compression for more information.
 */

// heif_uncompressed_component_type and heif_bayer_pattern_pixel are defined in heif_uncompressed_types.h.

// Set a Bayer / filter array pattern on an image.
// The pattern is a 2D array of component indices with dimensions pattern_width x pattern_height.
// The number of entries in patternPixels must be pattern_width * pattern_height.
// The component_index values are indices into the cmpd component definition table.
// On the encoder path, these indices are generated by heif_image_add_component() and the
// encoder adds reference components to cmpd for pattern entries that don't have image planes.
// On the decoder path, they come directly from the cpat box.
LIBHEIF_API
heif_error heif_image_set_bayer_pattern(heif_image*,
                                        uint16_t pattern_width,
                                        uint16_t pattern_height,
                                        const heif_bayer_pattern_pixel* patternPixels);

// Returns whether the image has a Bayer / filter array pattern.
// If the image has a pattern, out_pattern_width and out_pattern_height are set.
// Either output pointer may be NULL if the caller does not need that value.
LIBHEIF_API
int heif_image_has_bayer_pattern(const heif_image*,
                                 uint16_t* out_pattern_width,
                                 uint16_t* out_pattern_height);

// Get the Bayer / filter array pattern pixels.
// The caller must provide an array large enough for pattern_width * pattern_height entries
// (use heif_image_has_bayer_pattern() to query the dimensions first).
// Returns heif_error_Ok on success, or an error if no pattern is set.
LIBHEIF_API
heif_error heif_image_get_bayer_pattern(const heif_image*,
                                        heif_bayer_pattern_pixel* out_patternPixels);

// --- Polarization pattern (ISO 23001-17, Section 6.1.5)

// Special float value indicating "no polarization filter" at a pattern position.
// On the wire this is the IEEE 754 bit pattern 0xFFFFFFFF (a signaling NaN).
// Test with heif_polarization_angle_is_no_filter() below, or with isnan()/std::isnan().

// Returns a float with the 0xFFFFFFFF bit pattern (NaN) representing "no polarization filter".
LIBHEIF_API
float heif_polarization_angle_no_filter(void);

// Returns non-zero if the given angle has the "no filter" bit pattern (0xFFFFFFFF).
LIBHEIF_API
int heif_polarization_angle_is_no_filter(float angle);

// Add a polarization pattern to an image.
// component_indices: array of component indices this pattern applies to (may be NULL if num_component_indices == 0,
//                    meaning the pattern applies to all components).
// polarization_angles: array of pattern_width * pattern_height float values.
//                      Each is an angle in degrees [0.0, 360.0), or heif_polarization_angle_no_filter() for "no filter".
// Multiple patterns can be added (one per distinct component group).
LIBHEIF_API
heif_error heif_image_add_polarization_pattern(heif_image*,
                                               uint32_t num_component_indices,
                                               const uint32_t* component_indices,
                                               uint16_t pattern_width,
                                               uint16_t pattern_height,
                                               const float* polarization_angles);

// Returns the number of polarization patterns on this image (0 if none).
LIBHEIF_API
int heif_image_get_number_of_polarization_patterns(const heif_image*);

// Get the sizes/dimensions of a polarization pattern (to allocate arrays for the data query).
LIBHEIF_API
heif_error heif_image_get_polarization_pattern_info(const heif_image*,
                                                    int pattern_index,
                                                    uint32_t* out_num_component_indices,
                                                    uint16_t* out_pattern_width,
                                                    uint16_t* out_pattern_height);

// Get the actual data of a polarization pattern.
// Caller must provide pre-allocated arrays:
//   out_component_indices: num_component_indices entries (may be NULL if num_component_indices == 0)
//   out_polarization_angles: pattern_width * pattern_height entries
LIBHEIF_API
heif_error heif_image_get_polarization_pattern_data(const heif_image*,
                                                    int pattern_index,
                                                    uint32_t* out_component_indices,
                                                    float* out_polarization_angles);

// Find the polarization pattern index that applies to a given component index.
// Returns the pattern index (>= 0), or -1 if no pattern matches.
// A pattern with an empty component list (component_count == 0) matches all components.
LIBHEIF_API
int heif_image_get_polarization_pattern_index_for_component(const heif_image*,
                                                            uint32_t component_index);


// --- Sensor bad pixels map (ISO 23001-17, Section 6.1.7)

// struct heif_bad_pixel is defined in heif_uncompressed_types.h.

// Add a sensor bad pixels map to an image.
// component_indices: array of component indices this map applies to (may be NULL if num_component_indices == 0,
//                    meaning the map applies to all components).
// Multiple maps can be added (one per distinct component group with different defects).
LIBHEIF_API
heif_error heif_image_add_sensor_bad_pixels_map(heif_image*,
                                                 uint32_t num_component_indices,
                                                 const uint32_t* component_indices,
                                                 int correction_applied,
                                                 uint32_t num_bad_rows,
                                                 const uint32_t* bad_rows,
                                                 uint32_t num_bad_columns,
                                                 const uint32_t* bad_columns,
                                                 uint32_t num_bad_pixels,
                                                 const struct heif_bad_pixel* bad_pixels);

// Returns the number of sensor bad pixels maps on this image (0 if none).
LIBHEIF_API
int heif_image_get_number_of_sensor_bad_pixels_maps(const heif_image*);

// Get the sizes of a sensor bad pixels map (to allocate arrays for the data query).
LIBHEIF_API
heif_error heif_image_get_sensor_bad_pixels_map_info(const heif_image*,
                                                      int map_index,
                                                      uint32_t* out_num_component_indices,
                                                      int* out_correction_applied,
                                                      uint32_t* out_num_bad_rows,
                                                      uint32_t* out_num_bad_columns,
                                                      uint32_t* out_num_bad_pixels);

// Get the actual data of a sensor bad pixels map.
// Caller must provide pre-allocated arrays:
//   out_component_indices: num_component_indices entries (may be NULL if num_component_indices == 0)
//   out_bad_rows: num_bad_rows entries (may be NULL if num_bad_rows == 0)
//   out_bad_columns: num_bad_columns entries (may be NULL if num_bad_columns == 0)
//   out_bad_pixels: num_bad_pixels entries (may be NULL if num_bad_pixels == 0)
LIBHEIF_API
heif_error heif_image_get_sensor_bad_pixels_map_data(const heif_image*,
                                                      int map_index,
                                                      uint32_t* out_component_indices,
                                                      uint32_t* out_bad_rows,
                                                      uint32_t* out_bad_columns,
                                                      struct heif_bad_pixel* out_bad_pixels);


// --- Sensor non-uniformity correction (ISO 23001-17, Section 6.1.6)

// Add a sensor non-uniformity correction table to an image.
// component_indices: array of component indices this NUC applies to (may be NULL if num_component_indices == 0,
//                    meaning it applies to all components).
// nuc_gains and nuc_offsets: arrays of image_width * image_height float values.
// Correction equation: y = nuc_gain * x + nuc_offset.
// Multiple NUC tables can be added (one per distinct component group).
LIBHEIF_API
heif_error heif_image_add_sensor_nuc(heif_image*,
                                      uint32_t num_component_indices,
                                      const uint32_t* component_indices,
                                      int nuc_is_applied,
                                      uint32_t image_width,
                                      uint32_t image_height,
                                      const float* nuc_gains,
                                      const float* nuc_offsets);

// Returns the number of sensor NUC tables on this image (0 if none).
LIBHEIF_API
int heif_image_get_number_of_sensor_nucs(const heif_image*);

// Get the sizes of a sensor NUC table (to allocate arrays for the data query).
LIBHEIF_API
heif_error heif_image_get_sensor_nuc_info(const heif_image*,
                                           int nuc_index,
                                           uint32_t* out_num_component_indices,
                                           int* out_nuc_is_applied,
                                           uint32_t* out_image_width,
                                           uint32_t* out_image_height);

// Get the actual data of a sensor NUC table.
// Caller must provide pre-allocated arrays:
//   out_component_indices: num_component_indices entries (may be NULL if num_component_indices == 0)
//   out_nuc_gains: image_width * image_height entries
//   out_nuc_offsets: image_width * image_height entries
LIBHEIF_API
heif_error heif_image_get_sensor_nuc_data(const heif_image*,
                                           int nuc_index,
                                           uint32_t* out_component_indices,
                                           float* out_nuc_gains,
                                           float* out_nuc_offsets);


// heif_chroma420_sample_location is defined in heif_uncompressed_types.h.

// --- Chroma sample location (ISO 23001-17, Section 6.1.4)

// Set the chroma sample location on an image.
// chroma_location must be in the range 0-6 (see heif_chroma420_sample_location).
LIBHEIF_API
heif_error heif_image_set_chroma_location(heif_image*, uint8_t chroma_location);

// Returns non-zero if the image has a chroma sample location set.
LIBHEIF_API
int heif_image_has_chroma_location(const heif_image*);

// Returns the chroma sample location (0-6), or 0 if none is set.
LIBHEIF_API
uint8_t heif_image_get_chroma_location(const heif_image*);


// --- 'unci' images

// heif_unci_compression and heif_unci_image_parameters are defined in heif_uncompressed_types.h.

LIBHEIF_API
heif_unci_image_parameters* heif_unci_image_parameters_alloc(void);

LIBHEIF_API
void heif_unci_image_parameters_copy(heif_unci_image_parameters* dst,
                                     const heif_unci_image_parameters* src);

LIBHEIF_API
void heif_unci_image_parameters_release(heif_unci_image_parameters*);


/*
 * This adds an empty iso23001-17 (uncompressed) image to the HEIF file.
 * The actual image data is added later using heif_context_add_image_tile().
 * If you do not need tiling, you can use heif_context_encode_image() instead.
 * However, this will by default disable any compression and any control about
 * the data layout.
 *
 * @param ctx The file context
 * @param parameters The parameters for the image, must not be NULL.
 * @param encoding_options Optional, may be NULL.
 * @param prototype An image with the same channel configuration as the image data
 *                  that will be later inserted. The image size need not match this.
 *                  Must not be NULL.
 * @param out_unci_image_handle Returns a handle to the image. The caller is responsible for freeing it.
 *                  Must not be NULL because this is required to fill in image data.
 * @return Returns an error if the passed parameters are incorrect.
 *         If ISO23001-17 images are not supported, returns heif_error_Unsupported_feature.
 */
LIBHEIF_API
heif_error heif_context_add_empty_unci_image(heif_context* ctx,
                                             const heif_unci_image_parameters* parameters,
                                             const heif_encoding_options* encoding_options,
                                             const heif_image* prototype,
                                             heif_image_handle** out_unci_image_handle);

// heif_channel_datatype, heif_complex32, heif_complex64 are defined in heif_uncompressed_types.h.

// --- index-based component access (for ISO 23001-17 multi-component images)

// Returns the number of components that have pixel data (planes) in this image.
LIBHEIF_API
uint32_t heif_image_get_number_of_used_components(const heif_image*);

// Returns the total number of components declared in the cmpd box.
LIBHEIF_API
uint32_t heif_image_get_total_number_of_cmpd_components(const heif_image*);

// Fills `out_component_indices` with the valid component indices.
// The caller must allocate an array of at least heif_image_get_number_of_used_components() elements.
LIBHEIF_API
void heif_image_get_used_component_indices(const heif_image*, uint32_t* out_component_indices);

LIBHEIF_API
enum heif_channel heif_image_get_component_channel(const heif_image*, uint32_t component_idx);

LIBHEIF_API
uint32_t heif_image_get_component_width(const heif_image*, uint32_t component_idx);

LIBHEIF_API
uint32_t heif_image_get_component_height(const heif_image*, uint32_t component_idx);

LIBHEIF_API
int heif_image_get_component_bits_per_pixel(const heif_image*, uint32_t component_idx);

LIBHEIF_API
uint16_t heif_image_get_component_type(const heif_image*, uint32_t component_idx);

LIBHEIF_API
heif_error heif_image_add_component(heif_image* image,
                                    int width, int height,
                                    uint16_t component_type,
                                    heif_channel_datatype datatype,
                                    int bit_depth,
                                    uint32_t* out_component_idx);

LIBHEIF_API
const uint8_t* heif_image_get_component_readonly(const heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
uint8_t* heif_image_get_component(heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
const uint16_t* heif_image_get_component_uint16_readonly(const heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
uint16_t* heif_image_get_component_uint16(heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
const uint32_t* heif_image_get_component_uint32_readonly(const heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
uint32_t* heif_image_get_component_uint32(heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
const uint64_t* heif_image_get_component_uint64_readonly(const heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
uint64_t* heif_image_get_component_uint64(heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
const int8_t* heif_image_get_component_int8_readonly(const heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
int8_t* heif_image_get_component_int8(heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
const int16_t* heif_image_get_component_int16_readonly(const heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
int16_t* heif_image_get_component_int16(heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
const int32_t* heif_image_get_component_int32_readonly(const heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
int32_t* heif_image_get_component_int32(heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
const int64_t* heif_image_get_component_int64_readonly(const heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
int64_t* heif_image_get_component_int64(heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
const float* heif_image_get_component_float32_readonly(const heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
float* heif_image_get_component_float32(heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
const double* heif_image_get_component_float64_readonly(const heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
double* heif_image_get_component_float64(heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
const heif_complex32* heif_image_get_component_complex32_readonly(const heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
heif_complex32* heif_image_get_component_complex32(heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
const heif_complex64* heif_image_get_component_complex64_readonly(const heif_image*, uint32_t component_idx, size_t* out_stride);

LIBHEIF_API
heif_complex64* heif_image_get_component_complex64(heif_image*, uint32_t component_idx, size_t* out_stride);


// --- GIMI component content IDs (set before encoding)

// Set a GIMI component content ID for a single cmpd component.
// If the internal array is too small, it will be resized (new entries default to empty strings).
// These are written into an ItemComponentContentIDProperty box during encoding.
LIBHEIF_API
void heif_image_set_gimi_component_content_id(heif_image*,
                                              uint32_t component_idx,
                                              const char* content_id);

#ifdef __cplusplus
}
#endif

#endif
